var hierarchy =
[
    [ "EasyKiConverter::AltiumBinaryWriter", "classEasyKiConverter_1_1AltiumBinaryWriter.html", null ],
    [ "EasyKiConverter::AltiumPcbArc", "structEasyKiConverter_1_1AltiumPcbArc.html", null ],
    [ "EasyKiConverter::AltiumPcbComponent", "structEasyKiConverter_1_1AltiumPcbComponent.html", null ],
    [ "EasyKiConverter::AltiumPcbComponentBody", "structEasyKiConverter_1_1AltiumPcbComponentBody.html", null ],
    [ "EasyKiConverter::AltiumPcbExtendedPrimitiveInfo", "structEasyKiConverter_1_1AltiumPcbExtendedPrimitiveInfo.html", null ],
    [ "EasyKiConverter::AltiumPcbFill", "structEasyKiConverter_1_1AltiumPcbFill.html", null ],
    [ "EasyKiConverter::AltiumPcbLibWriter", "classEasyKiConverter_1_1AltiumPcbLibWriter.html", null ],
    [ "EasyKiConverter::AltiumPcbPad", "structEasyKiConverter_1_1AltiumPcbPad.html", null ],
    [ "EasyKiConverter::AltiumPcbRegion", "structEasyKiConverter_1_1AltiumPcbRegion.html", null ],
    [ "EasyKiConverter::AltiumPcbText", "structEasyKiConverter_1_1AltiumPcbText.html", null ],
    [ "EasyKiConverter::AltiumPcbTrack", "structEasyKiConverter_1_1AltiumPcbTrack.html", null ],
    [ "EasyKiConverter::AltiumSchArc", "structEasyKiConverter_1_1AltiumSchArc.html", null ],
    [ "EasyKiConverter::AltiumSchComponent", "structEasyKiConverter_1_1AltiumSchComponent.html", null ],
    [ "EasyKiConverter::AltiumSchEllipse", "structEasyKiConverter_1_1AltiumSchEllipse.html", null ],
    [ "EasyKiConverter::AltiumSchLibWriter", "classEasyKiConverter_1_1AltiumSchLibWriter.html", null ],
    [ "EasyKiConverter::AltiumSchLine", "structEasyKiConverter_1_1AltiumSchLine.html", null ],
    [ "EasyKiConverter::AltiumSchPath", "structEasyKiConverter_1_1AltiumSchPath.html", null ],
    [ "EasyKiConverter::AltiumSchPin", "structEasyKiConverter_1_1AltiumSchPin.html", null ],
    [ "EasyKiConverter::AltiumSchPolygon", "structEasyKiConverter_1_1AltiumSchPolygon.html", null ],
    [ "EasyKiConverter::AltiumSchPolyline", "structEasyKiConverter_1_1AltiumSchPolyline.html", null ],
    [ "EasyKiConverter::AltiumSchRectangle", "structEasyKiConverter_1_1AltiumSchRectangle.html", null ],
    [ "EasyKiConverter::AltiumSchText", "structEasyKiConverter_1_1AltiumSchText.html", null ],
    [ "EasyKiConverter::AtomicFileWriter", "classEasyKiConverter_1_1AtomicFileWriter.html", null ],
    [ "EasyKiConverter::IR::GeometryNormalizer::BBoxOrigin", "structEasyKiConverter_1_1IR_1_1GeometryNormalizer_1_1BBoxOrigin.html", null ],
    [ "EasyKiConverter::BoundedThreadSafeQueue< T >", "classEasyKiConverter_1_1BoundedThreadSafeQueue.html", null ],
    [ "EasyKiConverter::CacheHealthManager", "classEasyKiConverter_1_1CacheHealthManager.html", null ],
    [ "EasyKiConverter::ComponentService::CacheLoadResult", "structEasyKiConverter_1_1ComponentService_1_1CacheLoadResult.html", null ],
    [ "EasyKiConverter::CachePruner", "classEasyKiConverter_1_1CachePruner.html", null ],
    [ "EasyKiConverter::CacheRepository", "classEasyKiConverter_1_1CacheRepository.html", null ],
    [ "EasyKiConverter::CadDataLoader", "classEasyKiConverter_1_1CadDataLoader.html", null ],
    [ "EasyKiConverter::CadFetchTaskResult", "structEasyKiConverter_1_1CadFetchTaskResult.html", null ],
    [ "EasyKiConverter::CadParseResult", "structEasyKiConverter_1_1CadParseResult.html", null ],
    [ "EasyKiConverter::CliContext", "classEasyKiConverter_1_1CliContext.html", null ],
    [ "EasyKiConverter::CliPrinter", "classEasyKiConverter_1_1CliPrinter.html", null ],
    [ "EasyKiConverter::CommandLineParser", "classEasyKiConverter_1_1CommandLineParser.html", null ],
    [ "EasyKiConverter::TempFileManager::CommitItem", "structEasyKiConverter_1_1TempFileManager_1_1CommitItem.html", null ],
    [ "EasyKiConverter::CompletionGenerator", "classEasyKiConverter_1_1CompletionGenerator.html", null ],
    [ "EasyKiConverter::ComponentData", "classEasyKiConverter_1_1ComponentData.html", null ],
    [ "EasyKiConverter::ComponentExportStatus", "structEasyKiConverter_1_1ComponentExportStatus.html", null ],
    [ "EasyKiConverter::IR::ComponentIR", "structEasyKiConverter_1_1IR_1_1ComponentIR.html", null ],
    [ "EasyKiConverter::DebugExportHelper", "classEasyKiConverter_1_1DebugExportHelper.html", null ],
    [ "GzipUtils::DecompressResult", "structGzipUtils_1_1DecompressResult.html", null ],
    [ "EasyKiConverter::OLECompoundWriter::DirectoryEntry", "structEasyKiConverter_1_1OLECompoundWriter_1_1DirectoryEntry.html", null ],
    [ "EasyKiConverter::EasyedaFootprintImporter", "classEasyKiConverter_1_1EasyedaFootprintImporter.html", null ],
    [ "EasyKiConverter::EasyedaSymbolImporter", "classEasyKiConverter_1_1EasyedaSymbolImporter.html", null ],
    [ "EasyKiConverter::EasyedaUtils", "classEasyKiConverter_1_1EasyedaUtils.html", null ],
    [ "EasyKiConverter::ExporterFactory", "classEasyKiConverter_1_1ExporterFactory.html", null ],
    [ "EasyKiConverter::ExportItemStatus", "structEasyKiConverter_1_1ExportItemStatus.html", null ],
    [ "EasyKiConverter::ExportOptions", "structEasyKiConverter_1_1ExportOptions.html", null ],
    [ "EasyKiConverter::ExportOverallProgress", "structEasyKiConverter_1_1ExportOverallProgress.html", null ],
    [ "EasyKiConverter::ExportReportGenerator", "classEasyKiConverter_1_1ExportReportGenerator.html", null ],
    [ "EasyKiConverter::ExportStatistics", "structEasyKiConverter_1_1ExportStatistics.html", null ],
    [ "EasyKiConverter::ExportTypeProgress", "structEasyKiConverter_1_1ExportTypeProgress.html", null ],
    [ "EasyKiConverter::ExportWorkerHelpers", "classEasyKiConverter_1_1ExportWorkerHelpers.html", null ],
    [ "EasyKiConverter::ComponentService::FetchingComponent", "structEasyKiConverter_1_1ComponentService_1_1FetchingComponent.html", null ],
    [ "EasyKiConverter::FileReader", "classEasyKiConverter_1_1FileReader.html", null ],
    [ "EasyKiConverter::AltiumModels::FontEntry", "structEasyKiConverter_1_1AltiumModels_1_1FontEntry.html", null ],
    [ "EasyKiConverter::FootprintArc", "structEasyKiConverter_1_1FootprintArc.html", null ],
    [ "EasyKiConverter::IR::FootprintArcIR", "structEasyKiConverter_1_1IR_1_1FootprintArcIR.html", null ],
    [ "EasyKiConverter::FootprintBBox", "structEasyKiConverter_1_1FootprintBBox.html", null ],
    [ "EasyKiConverter::FootprintCircle", "structEasyKiConverter_1_1FootprintCircle.html", null ],
    [ "EasyKiConverter::IR::FootprintCircleIR", "structEasyKiConverter_1_1IR_1_1FootprintCircleIR.html", null ],
    [ "EasyKiConverter::IR::FootprintComponentIR", "structEasyKiConverter_1_1IR_1_1FootprintComponentIR.html", null ],
    [ "EasyKiConverter::FootprintData", "classEasyKiConverter_1_1FootprintData.html", null ],
    [ "EasyKiConverter::FootprintDataSerializer", "classEasyKiConverter_1_1FootprintDataSerializer.html", null ],
    [ "EasyKiConverter::FootprintGraphicsGenerator", "classEasyKiConverter_1_1FootprintGraphicsGenerator.html", null ],
    [ "EasyKiConverter::FootprintHole", "structEasyKiConverter_1_1FootprintHole.html", null ],
    [ "EasyKiConverter::IR::FootprintHoleIR", "structEasyKiConverter_1_1IR_1_1FootprintHoleIR.html", null ],
    [ "EasyKiConverter::FootprintInfo", "structEasyKiConverter_1_1FootprintInfo.html", null ],
    [ "EasyKiConverter::FootprintOutline", "structEasyKiConverter_1_1FootprintOutline.html", null ],
    [ "EasyKiConverter::IR::FootprintOutlineIR", "structEasyKiConverter_1_1IR_1_1FootprintOutlineIR.html", null ],
    [ "EasyKiConverter::FootprintPad", "structEasyKiConverter_1_1FootprintPad.html", null ],
    [ "EasyKiConverter::IR::FootprintPadIR", "structEasyKiConverter_1_1IR_1_1FootprintPadIR.html", null ],
    [ "EasyKiConverter::FootprintRectangle", "structEasyKiConverter_1_1FootprintRectangle.html", null ],
    [ "EasyKiConverter::IR::FootprintRectangleIR", "structEasyKiConverter_1_1IR_1_1FootprintRectangleIR.html", null ],
    [ "EasyKiConverter::IR::FootprintRegionIR", "structEasyKiConverter_1_1IR_1_1FootprintRegionIR.html", null ],
    [ "EasyKiConverter::FootprintSolidRegion", "structEasyKiConverter_1_1FootprintSolidRegion.html", null ],
    [ "EasyKiConverter::FootprintText", "structEasyKiConverter_1_1FootprintText.html", null ],
    [ "EasyKiConverter::IR::FootprintTextIR", "structEasyKiConverter_1_1IR_1_1FootprintTextIR.html", null ],
    [ "EasyKiConverter::FootprintTrack", "structEasyKiConverter_1_1FootprintTrack.html", null ],
    [ "EasyKiConverter::IR::FootprintTrackIR", "structEasyKiConverter_1_1IR_1_1FootprintTrackIR.html", null ],
    [ "EasyKiConverter::GeometryUtils", "classEasyKiConverter_1_1GeometryUtils.html", null ],
    [ "EasyKiConverter::IAppender", "classEasyKiConverter_1_1IAppender.html", [
      [ "EasyKiConverter::ConsoleAppender", "classEasyKiConverter_1_1ConsoleAppender.html", null ],
      [ "EasyKiConverter::FileAppender", "classEasyKiConverter_1_1FileAppender.html", null ]
    ] ],
    [ "EasyKiConverter::IExportWorker", "classEasyKiConverter_1_1IExportWorker.html", [
      [ "EasyKiConverter::DatasheetExportWorker", "classEasyKiConverter_1_1DatasheetExportWorker.html", null ],
      [ "EasyKiConverter::Model3DExportWorker", "classEasyKiConverter_1_1Model3DExportWorker.html", null ],
      [ "EasyKiConverter::PreviewImagesExportWorker", "classEasyKiConverter_1_1PreviewImagesExportWorker.html", null ]
    ] ],
    [ "EasyKiConverter::IFootprintExporter", "classEasyKiConverter_1_1IFootprintExporter.html", [
      [ "EasyKiConverter::ExporterAltiumFootprint", "classEasyKiConverter_1_1ExporterAltiumFootprint.html", null ],
      [ "EasyKiConverter::ExporterFootprint", "classEasyKiConverter_1_1ExporterFootprint.html", null ]
    ] ],
    [ "EasyKiConverter::IFormatter", "classEasyKiConverter_1_1IFormatter.html", [
      [ "EasyKiConverter::PatternFormatter", "classEasyKiConverter_1_1PatternFormatter.html", null ]
    ] ],
    [ "EasyKiConverter::IModel3DExporter", "classEasyKiConverter_1_1IModel3DExporter.html", [
      [ "EasyKiConverter::Exporter3DModel", "classEasyKiConverter_1_1Exporter3DModel.html", null ]
    ] ],
    [ "EasyKiConverter::AltiumSchComponent::Implementation", "structEasyKiConverter_1_1AltiumSchComponent_1_1Implementation.html", null ],
    [ "EasyKiConverter::INetworkClient", "classEasyKiConverter_1_1INetworkClient.html", [
      [ "EasyKiConverter::NetworkClient", "classEasyKiConverter_1_1NetworkClient.html", null ]
    ] ],
    [ "EasyKiConverter::ISymbolExporter", "classEasyKiConverter_1_1ISymbolExporter.html", [
      [ "EasyKiConverter::ExporterAltiumSymbol", "classEasyKiConverter_1_1ExporterAltiumSymbol.html", null ],
      [ "EasyKiConverter::ExporterSymbol", "classEasyKiConverter_1_1ExporterSymbol.html", null ]
    ] ],
    [ "EasyKiConverter::KiCadLibraryTableManager", "classEasyKiConverter_1_1KiCadLibraryTableManager.html", null ],
    [ "EasyKiConverter::LayerDefinition", "structEasyKiConverter_1_1LayerDefinition.html", null ],
    [ "EasyKiConverter::LayerMapper", "classEasyKiConverter_1_1LayerMapper.html", null ],
    [ "EasyKiConverter::LogRecord", "structEasyKiConverter_1_1LogRecord.html", null ],
    [ "EasyKiConverter::LogUtils", "classEasyKiConverter_1_1LogUtils.html", null ],
    [ "EasyKiConverter::MemoryMonitor", "classEasyKiConverter_1_1MemoryMonitor.html", null ],
    [ "EasyKiConverter::MemorySnapshot", "structEasyKiConverter_1_1MemorySnapshot.html", null ],
    [ "EasyKiConverter::AltiumPcbComponent::Model3D", "structEasyKiConverter_1_1AltiumPcbComponent_1_1Model3D.html", null ],
    [ "EasyKiConverter::Model3DBase", "structEasyKiConverter_1_1Model3DBase.html", null ],
    [ "EasyKiConverter::Model3DData", "classEasyKiConverter_1_1Model3DData.html", null ],
    [ "EasyKiConverter::IR::Model3DIR", "classEasyKiConverter_1_1IR_1_1Model3DIR.html", null ],
    [ "EasyKiConverter::IR::Model3DVec3", "structEasyKiConverter_1_1IR_1_1Model3DVec3.html", null ],
    [ "EasyKiConverter::NetworkClient::MutableResourceStats", "structEasyKiConverter_1_1NetworkClient_1_1MutableResourceStats.html", null ],
    [ "EasyKiConverter::NetworkDiagnostic", "structEasyKiConverter_1_1NetworkDiagnostic.html", null ],
    [ "EasyKiConverter::ComponentExportStatus::NetworkDiagnostics", "structEasyKiConverter_1_1ComponentExportStatus_1_1NetworkDiagnostics.html", null ],
    [ "EasyKiConverter::NetworkError", "classEasyKiConverter_1_1NetworkError.html", null ],
    [ "EasyKiConverter::NetworkResourceStats", "structEasyKiConverter_1_1NetworkResourceStats.html", null ],
    [ "EasyKiConverter::NetworkResult", "structEasyKiConverter_1_1NetworkResult.html", null ],
    [ "EasyKiConverter::NetworkRuntimeStats", "structEasyKiConverter_1_1NetworkRuntimeStats.html", null ],
    [ "EasyKiConverter::ObjectVisibility", "structEasyKiConverter_1_1ObjectVisibility.html", null ],
    [ "EasyKiConverter::OLECompoundWriter", "classEasyKiConverter_1_1OLECompoundWriter.html", null ],
    [ "EasyKiConverter::Model3DExportWorker::OutputPaths", "structEasyKiConverter_1_1Model3DExportWorker_1_1OutputPaths.html", null ],
    [ "EasyKiConverter::PathSecurity", "classEasyKiConverter_1_1PathSecurity.html", null ],
    [ "EasyKiConverter::NetworkClient::PendingAsyncRequest", "structEasyKiConverter_1_1NetworkClient_1_1PendingAsyncRequest.html", null ],
    [ "EasyKiConverter::PreloadProgress", "structEasyKiConverter_1_1PreloadProgress.html", null ],
    [ "QAbstractListModel", null, [
      [ "EasyKiConverter::ComponentListViewModel", "classEasyKiConverter_1_1ComponentListViewModel.html", null ]
    ] ],
    [ "QObject", null, [
      [ "EasyKiConverter::AsyncNetworkRequest", "classEasyKiConverter_1_1AsyncNetworkRequest.html", null ],
      [ "EasyKiConverter::BaseConverter", "classEasyKiConverter_1_1BaseConverter.html", [
        [ "EasyKiConverter::BatchConverter", "classEasyKiConverter_1_1BatchConverter.html", null ],
        [ "EasyKiConverter::BomConverter", "classEasyKiConverter_1_1BomConverter.html", null ],
        [ "EasyKiConverter::ComponentConverter", "classEasyKiConverter_1_1ComponentConverter.html", null ]
      ] ],
      [ "EasyKiConverter::BaseWorker", "classEasyKiConverter_1_1BaseWorker.html", [
        [ "EasyKiConverter::FetchWorker", "classEasyKiConverter_1_1FetchWorker.html", null ],
        [ "EasyKiConverter::NetworkWorker", "classEasyKiConverter_1_1NetworkWorker.html", null ]
      ] ],
      [ "EasyKiConverter::BomParser", "classEasyKiConverter_1_1BomParser.html", null ],
      [ "EasyKiConverter::CliConverter", "classEasyKiConverter_1_1CliConverter.html", null ],
      [ "EasyKiConverter::ComponentCacheService", "classEasyKiConverter_1_1ComponentCacheService.html", null ],
      [ "EasyKiConverter::ComponentDataCache", "classEasyKiConverter_1_1ComponentDataCache.html", null ],
      [ "EasyKiConverter::ComponentListItemData", "classEasyKiConverter_1_1ComponentListItemData.html", null ],
      [ "EasyKiConverter::ComponentQueueManager", "classEasyKiConverter_1_1ComponentQueueManager.html", null ],
      [ "EasyKiConverter::ComponentService", "classEasyKiConverter_1_1ComponentService.html", null ],
      [ "EasyKiConverter::ConfigManager", "classEasyKiConverter_1_1ConfigManager.html", null ],
      [ "EasyKiConverter::ConfigService", "classEasyKiConverter_1_1ConfigService.html", null ],
      [ "EasyKiConverter::DatasheetExportWorker", "classEasyKiConverter_1_1DatasheetExportWorker.html", null ],
      [ "EasyKiConverter::DatasheetExporter", "classEasyKiConverter_1_1DatasheetExporter.html", null ],
      [ "EasyKiConverter::EasyedaApi", "classEasyKiConverter_1_1EasyedaApi.html", null ],
      [ "EasyKiConverter::EasyedaImporter", "classEasyKiConverter_1_1EasyedaImporter.html", null ],
      [ "EasyKiConverter::ExportProgressViewModel", "classEasyKiConverter_1_1ExportProgressViewModel.html", null ],
      [ "EasyKiConverter::ExportSettingsViewModel", "classEasyKiConverter_1_1ExportSettingsViewModel.html", null ],
      [ "EasyKiConverter::ExportTargetModel", "classEasyKiConverter_1_1ExportTargetModel.html", null ],
      [ "EasyKiConverter::ExportTypeStage", "classEasyKiConverter_1_1ExportTypeStage.html", [
        [ "EasyKiConverter::DatasheetExportStage", "classEasyKiConverter_1_1DatasheetExportStage.html", null ],
        [ "EasyKiConverter::FootprintExportStage", "classEasyKiConverter_1_1FootprintExportStage.html", null ],
        [ "EasyKiConverter::Model3DExportStage", "classEasyKiConverter_1_1Model3DExportStage.html", null ],
        [ "EasyKiConverter::PreviewImagesExportStage", "classEasyKiConverter_1_1PreviewImagesExportStage.html", null ],
        [ "EasyKiConverter::SymbolExportStage", "classEasyKiConverter_1_1SymbolExportStage.html", null ]
      ] ],
      [ "EasyKiConverter::Exporter3DModel", "classEasyKiConverter_1_1Exporter3DModel.html", null ],
      [ "EasyKiConverter::FileUtils", "classEasyKiConverter_1_1FileUtils.html", null ],
      [ "EasyKiConverter::JLCDatasheet", "classEasyKiConverter_1_1JLCDatasheet.html", null ],
      [ "EasyKiConverter::LanguageManager", "classEasyKiConverter_1_1LanguageManager.html", null ],
      [ "EasyKiConverter::LcscImageService", "classEasyKiConverter_1_1LcscImageService.html", null ],
      [ "EasyKiConverter::Logger", "classEasyKiConverter_1_1Logger.html", null ],
      [ "EasyKiConverter::MediaFetchWorker", "classEasyKiConverter_1_1MediaFetchWorker.html", null ],
      [ "EasyKiConverter::Model3DExportWorker", "classEasyKiConverter_1_1Model3DExportWorker.html", null ],
      [ "EasyKiConverter::NetworkClient", "classEasyKiConverter_1_1NetworkClient.html", null ],
      [ "EasyKiConverter::ParallelExportService", "classEasyKiConverter_1_1ParallelExportService.html", null ],
      [ "EasyKiConverter::ParallelFetchContext", "classEasyKiConverter_1_1ParallelFetchContext.html", null ],
      [ "EasyKiConverter::PipelineCompletionHandler", "classEasyKiConverter_1_1PipelineCompletionHandler.html", null ],
      [ "EasyKiConverter::PreviewImageExporter", "classEasyKiConverter_1_1PreviewImageExporter.html", null ],
      [ "EasyKiConverter::PreviewImagesExportWorker", "classEasyKiConverter_1_1PreviewImagesExportWorker.html", null ],
      [ "EasyKiConverter::ProcessWorker", "classEasyKiConverter_1_1ProcessWorker.html", null ],
      [ "EasyKiConverter::SystemTrayManager", "classEasyKiConverter_1_1SystemTrayManager.html", null ],
      [ "EasyKiConverter::TempFileManager", "classEasyKiConverter_1_1TempFileManager.html", null ],
      [ "EasyKiConverter::ThemeSettingsViewModel", "classEasyKiConverter_1_1ThemeSettingsViewModel.html", null ],
      [ "EasyKiConverter::UpdateCheckerService", "classEasyKiConverter_1_1UpdateCheckerService.html", null ],
      [ "EasyKiConverter::ValidationStateManager", "classEasyKiConverter_1_1ValidationStateManager.html", null ],
      [ "EasyKiConverter::WriteWorker", "classEasyKiConverter_1_1WriteWorker.html", null ]
    ] ],
    [ "QRunnable", null, [
      [ "EasyKiConverter::BaseWorker", "classEasyKiConverter_1_1BaseWorker.html", null ],
      [ "EasyKiConverter::DatasheetExportWorker", "classEasyKiConverter_1_1DatasheetExportWorker.html", null ],
      [ "EasyKiConverter::MediaFetchWorker", "classEasyKiConverter_1_1MediaFetchWorker.html", null ],
      [ "EasyKiConverter::Model3DExportWorker", "classEasyKiConverter_1_1Model3DExportWorker.html", null ],
      [ "EasyKiConverter::PreviewImageEncodeRunnable", "classEasyKiConverter_1_1PreviewImageEncodeRunnable.html", null ],
      [ "EasyKiConverter::PreviewImagesExportWorker", "classEasyKiConverter_1_1PreviewImagesExportWorker.html", null ],
      [ "EasyKiConverter::ProcessWorker", "classEasyKiConverter_1_1ProcessWorker.html", null ],
      [ "EasyKiConverter::WriteWorker", "classEasyKiConverter_1_1WriteWorker.html", null ]
    ] ],
    [ "EasyKiConverter::QtLogAdapter", "classEasyKiConverter_1_1QtLogAdapter.html", null ],
    [ "EasyKiConverter::RequestProfile", "structEasyKiConverter_1_1RequestProfile.html", null ],
    [ "EasyKiConverter::RequestProfiles", "structEasyKiConverter_1_1RequestProfiles.html", null ],
    [ "EasyKiConverter::RetryPolicy", "structEasyKiConverter_1_1RetryPolicy.html", null ],
    [ "EasyKiConverter::ScopedDataClearer", "classEasyKiConverter_1_1ScopedDataClearer.html", null ],
    [ "EasyKiConverter::ScopedTracer", "classEasyKiConverter_1_1ScopedTracer.html", null ],
    [ "EasyKiConverter::OLECompoundWriter::StorageNode", "structEasyKiConverter_1_1OLECompoundWriter_1_1StorageNode.html", null ],
    [ "EasyKiConverter::OLECompoundWriter::StreamData", "structEasyKiConverter_1_1OLECompoundWriter_1_1StreamData.html", null ],
    [ "EasyKiConverter::GeometryUtils::SvgArcEndpoints", "structEasyKiConverter_1_1GeometryUtils_1_1SvgArcEndpoints.html", null ],
    [ "EasyKiConverter::GeometryUtils::SvgArcResult", "structEasyKiConverter_1_1GeometryUtils_1_1SvgArcResult.html", null ],
    [ "EasyKiConverter::IR::SvgArcResult", "structEasyKiConverter_1_1IR_1_1SvgArcResult.html", null ],
    [ "EasyKiConverter::SvgPathParser", "classEasyKiConverter_1_1SvgPathParser.html", null ],
    [ "EasyKiConverter::GeometryUtils::SvgPoint", "structEasyKiConverter_1_1GeometryUtils_1_1SvgPoint.html", null ],
    [ "EasyKiConverter::SymbolArc", "structEasyKiConverter_1_1SymbolArc.html", null ],
    [ "EasyKiConverter::IR::SymbolArcIR", "structEasyKiConverter_1_1IR_1_1SymbolArcIR.html", null ],
    [ "EasyKiConverter::SymbolBBox", "structEasyKiConverter_1_1SymbolBBox.html", null ],
    [ "EasyKiConverter::SymbolCircle", "structEasyKiConverter_1_1SymbolCircle.html", null ],
    [ "EasyKiConverter::IR::SymbolCircleIR", "structEasyKiConverter_1_1IR_1_1SymbolCircleIR.html", null ],
    [ "EasyKiConverter::IR::SymbolComponentIR", "structEasyKiConverter_1_1IR_1_1SymbolComponentIR.html", null ],
    [ "EasyKiConverter::SymbolData", "classEasyKiConverter_1_1SymbolData.html", null ],
    [ "EasyKiConverter::SymbolDataSerializer", "classEasyKiConverter_1_1SymbolDataSerializer.html", null ],
    [ "EasyKiConverter::SymbolEllipse", "structEasyKiConverter_1_1SymbolEllipse.html", null ],
    [ "EasyKiConverter::IR::SymbolEllipseIR", "structEasyKiConverter_1_1IR_1_1SymbolEllipseIR.html", null ],
    [ "EasyKiConverter::SymbolGraphicsGenerator", "classEasyKiConverter_1_1SymbolGraphicsGenerator.html", null ],
    [ "EasyKiConverter::SymbolInfo", "structEasyKiConverter_1_1SymbolInfo.html", null ],
    [ "EasyKiConverter::SymbolPart", "structEasyKiConverter_1_1SymbolPart.html", null ],
    [ "EasyKiConverter::SymbolPath", "structEasyKiConverter_1_1SymbolPath.html", null ],
    [ "EasyKiConverter::IR::SymbolPathIR", "structEasyKiConverter_1_1IR_1_1SymbolPathIR.html", null ],
    [ "EasyKiConverter::SymbolPin", "structEasyKiConverter_1_1SymbolPin.html", null ],
    [ "EasyKiConverter::SymbolPinClock", "structEasyKiConverter_1_1SymbolPinClock.html", null ],
    [ "EasyKiConverter::IR::SymbolPinDisplay", "structEasyKiConverter_1_1IR_1_1SymbolPinDisplay.html", null ],
    [ "EasyKiConverter::SymbolPinDot", "structEasyKiConverter_1_1SymbolPinDot.html", null ],
    [ "EasyKiConverter::SymbolPinDotBis", "structEasyKiConverter_1_1SymbolPinDotBis.html", null ],
    [ "EasyKiConverter::IR::SymbolPinIR", "structEasyKiConverter_1_1IR_1_1SymbolPinIR.html", null ],
    [ "EasyKiConverter::SymbolPinName", "structEasyKiConverter_1_1SymbolPinName.html", null ],
    [ "EasyKiConverter::SymbolPinPath", "structEasyKiConverter_1_1SymbolPinPath.html", null ],
    [ "EasyKiConverter::SymbolPinSerializer", "classEasyKiConverter_1_1SymbolPinSerializer.html", null ],
    [ "EasyKiConverter::SymbolPinSettings", "structEasyKiConverter_1_1SymbolPinSettings.html", null ],
    [ "EasyKiConverter::IR::SymbolPinStyle", "structEasyKiConverter_1_1IR_1_1SymbolPinStyle.html", null ],
    [ "EasyKiConverter::SymbolPolygon", "structEasyKiConverter_1_1SymbolPolygon.html", null ],
    [ "EasyKiConverter::IR::SymbolPolygonIR", "structEasyKiConverter_1_1IR_1_1SymbolPolygonIR.html", null ],
    [ "EasyKiConverter::SymbolPolyline", "structEasyKiConverter_1_1SymbolPolyline.html", null ],
    [ "EasyKiConverter::IR::SymbolPolylineIR", "structEasyKiConverter_1_1IR_1_1SymbolPolylineIR.html", null ],
    [ "EasyKiConverter::SymbolRectangle", "structEasyKiConverter_1_1SymbolRectangle.html", null ],
    [ "EasyKiConverter::IR::SymbolRectangleIR", "structEasyKiConverter_1_1IR_1_1SymbolRectangleIR.html", null ],
    [ "EasyKiConverter::SymbolShapeSerializer", "classEasyKiConverter_1_1SymbolShapeSerializer.html", null ],
    [ "EasyKiConverter::SymbolText", "structEasyKiConverter_1_1SymbolText.html", null ],
    [ "EasyKiConverter::IR::SymbolTextIR", "structEasyKiConverter_1_1IR_1_1SymbolTextIR.html", null ],
    [ "EasyKiConverter::ExportTargetModel::TargetInfo", "structEasyKiConverter_1_1ExportTargetModel_1_1TargetInfo.html", null ],
    [ "EasyKiConverter::Model3DExportStage::TempFilePaths", "structEasyKiConverter_1_1Model3DExportStage_1_1TempFilePaths.html", null ],
    [ "EasyKiConverter::TestableSingleton< T >", "classEasyKiConverter_1_1TestableSingleton.html", null ],
    [ "EasyKiConverter::TestableSingleton< NetworkClient >", "classEasyKiConverter_1_1TestableSingleton.html", [
      [ "EasyKiConverter::NetworkClient", "classEasyKiConverter_1_1NetworkClient.html", null ]
    ] ],
    [ "EasyKiConverter::TimeLogger", "classEasyKiConverter_1_1TimeLogger.html", null ]
];