# -*- mode: python ; coding: utf-8 -*-

import sys
import os
block_cipher = None

a = Analysis(
    ['../src/ui/pyqt6/main.py'],
    pathex=['.', '../src'],
    binaries=[],
    datas=[
        ('../src/ui/pyqt6/resources/app_icon.ico', 'resources'),
        ('../src/ui/pyqt6/resources/app_icon.ico', '.'),
        ('../src/ui/pyqt6/resources', 'resources'),
    ],
    hiddenimports=[
        'PyQt6.QtCore',
        'PyQt6.QtGui',
        'PyQt6.QtWidgets',
        'PyQt6.QtNetwork',
        'PyQt6.QtOpenGL',
        'PyQt6.QtOpenGLWidgets',
        'pandas',
        'pandas._libs',
        'pandas._libs.tslibs',
        'pandas._libs.tslibs.timedeltas',
        'pandas._libs.tslibs.nattype',
        'pandas._libs.tslibs.np_datetime',
        'pandas._libs.skiplist',
        'pandas.io',
        'pandas.io.common',
        'pandas.io.parsers',
        'pandas.io.parsers.readers',
        'pandas._config.config',
        'openpyxl',
        'openpyxl.workbook',
        'openpyxl.workbook.workbook',
        'openpyxl.worksheet',
        'openpyxl.worksheet.worksheet',
        'requests',
        'requests.adapters',
        'requests.auth',
        'requests.cookies',
        'requests.exceptions',
        'requests.hooks',
        'requests.models',
        'requests.sessions',
        'requests.status_codes',
        'requests.structures',
        'requests.utils',
        'pydantic',
        'pydantic_core',
        'pydantic.main',
        'pydantic.types',
        'pydantic.fields',
        'numpy',
        'numpy._core',
        'numpy._core._multiarray_umath',
        'numpy._core.multiarray',
        'numpy._core.umath',
        'numpy._core.numeric',
        'numpy.linalg',
        'numpy.linalg._umath_linalg',
        'numpy.linalg.lapack_lite',
        'numpy.random',
        'numpy.random._pickle',
        'numpy.random.common',
        'numpy.random.bounded_integers',
        'numpy.random.entropy',
        'numpy.random.bit_generator',
        'certifi',
        'urllib3',
        'urllib3.connection',
        'urllib3.connectionpool',
        'urllib3.contrib',
        'urllib3.contrib.pyopenssl',
        'urllib3.exceptions',
        'urllib3.fields',
        'urllib3.filepost',
        'urllib3.packages',
        'urllib3.packages.ssl_match_hostname',
        'urllib3.poolmanager',
        'urllib3.request',
        'urllib3.response',
        'urllib3.util',
        'urllib3.util.connection',
        'urllib3.util.request',
        'urllib3.util.response',
        'urllib3.util.retry',
        'urllib3.util.ssl_',
        'urllib3.util.timeout',
        'urllib3.util.url',
        'charset_normalizer',
        'idna',
        'python_dateutil',
        'python_dateutil.parser',
        'pytz',
        'tzdata',
        'et_xmlfile',
        'six',
        'annotated_types',
        'typing_extensions',
        'typing_inspection'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'scipy',
        'jinja2',
        'werkzeug',
        'blinker',
        'click',
        'markupsafe'
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='EasyKiConverter',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='../src/ui/pyqt6/resources/app_icon.ico' if sys.platform.startswith('win') and os.path.exists('../src/ui/pyqt6/resources/app_icon.ico') else None
)