name: Security

on:
  schedule:
    - cron: '0 0 * * 0'  # 每周日运行
  pull_request:
    branches: [ master, dev, 'v*' ]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-24.04
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Dependency Review
        uses: actions/dependency-review-action@2031cfc080254a8a887f58cffee85186f0e49e48 # v4.9.0
        with:
          fail-on-severity: moderate
          allow-licenses: GPL-3.0-only, GPL-3.0-or-later, MIT, BSD-2-Clause, BSD-3-Clause, BSD-3-Clause-Clear, Apache-2.0
